language: cpp

dist: trusty

branches:
  except:
  - gh-pages

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - eval "${MATRIX_EVAL}"

script:
    - mkdir build
    - cd build
    - cp ../include/abulafia/abulafia_all.h ./abulafia_all_ref.h
    - rm ../include/abulafia/abulafia_all.h
    - cmake -DCMAKE_VERBOSE_MAKEFILE=ON ..
    - cmake --build .
    - ctest

notifications:
  email: false