branches:
    only:
        - master
skip_tags: true
matrix:
    fast_finish: true
build_script:
    - git submodule init
    - git submodule update
    - mkdir build
    - cd build
    - cmake -G "Visual Studio 15 2017" ..
    - cmake --build .
    - ctest