site_name: Abulafia Documentation
theme: material
extra:
  palette:
    primary: 'Amber'
    accent: 'Deep Orange'
  feature:
    tabs: true
repo_name: 'FrancoisChabot/abulafia'
repo_url: 'https://github.com/FrancoisChabot/abulafia'

markdown_extensions:
  - footnotes
pages:
- Home: 'index.md'
- User Guide:
  - 'Installation': 'guide/01_installation.md'
  - 'Parsers': 'guide/02_parsers.md'
  - 'Skippers': 'guide/03_skippers.md'
- Reference:
  - 'Quick Reference': 'patterns/reference.md'
  - 'Leaf parsers':
      - 'Integer' : 'patterns/leaf/numeric/int.md'
      - 'Character' : 'patterns/leaf/character.md'
      - 'End-of-input' : 'patterns/leaf/eoi.md'
      - 'Fail' : 'patterns/leaf/fail.md'
      - 'Literal' : 'patterns/leaf/literal.md'
      - 'Pass' : 'patterns/leaf/pass.md'
      - 'Symbol' : 'patterns/leaf/Symbol.md'
  - 'Unary parsers': 
    - 'not' : 'patterns/unary/not.md'
    - 'repeat' : 'patterns/unary/repeat.md'
  - 'Binary Parsers': 
    - 'except' : 'patterns/binary/except.md'
    - 'list' : 'patterns/binary/list.md'
  - 'Nary parsers': 
    - 'Alternative' : 'patterns/nary/alternative.md'
    - 'Sequence' : 'patterns/nary/sequence.md'
  - 'Special parsers':
    - 'Recursive' : 'patterns/recur.md'
    - 'Semantic Action' : 'patterns/action.md'
