site_name: Abulafia Documentation
theme: material
extra_css: 
    - custom.css
markdown_extensions:
  - footnotes
pages:
- Home: 'index.md'
- User Guide:
  - 'Installation': 'guide/01_installation.md'
  - 'Introduction': 'guide/02_introduction.md'
- Reference:
  - 'Quick Reference': 'patterns/reference.md'
  - 'Leaf parsers':
      - 'Integer' : 'patterns/leaf/numeric/int.md'
      - 'Character' : 'patterns/leaf/character.md'
      - 'End-of-input' : 'patterns/leaf/eoi.md'
      - 'Fail' : 'patterns/leaf/fail.md'
      - 'Literal' : 'patterns/leaf/literal.md'
      - 'Pass' : 'patterns/leaf/pass.md'
      - 'Symbol' : 'patterns/leaf/Symbol.md'
  - 'Unary parsers': 
    - 'not' : 'patterns/unary/not.md'
    - 'repeat' : 'patterns/unary/repeat.md'
  - 'Binary Parsers': 
    - 'except' : 'patterns/binary/except.md'
    - 'list' : 'patterns/binary/list.md'
  - 'Nary parsers': 
    - 'Alternative' : 'patterns/nary/alternative.md'
    - 'Sequence' : 'patterns/nary/sequence.md'
  - 'Special parsers':
    - 'Recursive' : 'patterns/recur.md'
    - 'Semantic Action' : 'patterns/action.md'